# Generated by Django 3.1.7 on 2021-03-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='verbose name Title')),
                ('details', models.TextField(verbose_name='verbose name Details/Description')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='verbose name')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scroe', models.CharField(max_length=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2m.game')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2m.people')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='people',
            field=models.ManyToManyField(related_name='games', through='m2m.PeopleGame', to='m2m.People'),
        ),
    ]
