# Generated by Django 3.1.7 on 2021-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='up/'),
        ),
    ]
