# Generated by Django 3.1.7 on 2021-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0003_auto_20210328_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='upload',
            field=models.FileField(blank=True, default='/home/rana/Downloads/1082411506.doc', null=True, upload_to='up/'),
        ),
    ]
