# Generated by Django 3.1.7 on 2021-03-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0005_auto_20210328_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='upload',
        ),
        migrations.AddField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, default='/home/rana/Pictures/images.png', null=True, upload_to='up/'),
        ),
    ]
