# Generated by Django 3.1.7 on 2021-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0006_auto_20210328_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='up/'),
        ),
    ]
