# Generated by Django 3.1.7 on 2021-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0007_auto_20210328_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patternName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('units', models.CharField(choices=[('szt', 'szt'), ('m', 'm'), ('komp', 'komp')], default='szt', max_length=10)),
                ('description', models.TextField()),
                ('pattern', models.ManyToManyField(related_name='patterns', to='stackoverflow.Pattern')),
            ],
        ),
    ]
