# Generated by Django 3.1.7 on 2021-03-28 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stackoverflow', '0008_part_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(default=1, max_length=1)),
                ('created_on', models.DateTimeField()),
                ('likes', models.ManyToManyField(related_name='realtednamepost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
