# Generated by Django 3.1.7 on 2021-04-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0017_item_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stackoverflow.post',),
        ),
    ]
