# Generated by Django 3.1.7 on 2021-04-13 14:02

from django.db import migrations, models
import stackoverflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0018_mypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=stackoverflow.models.user_directory_path),
        ),
    ]
