# Generated by Django 3.1.7 on 2021-04-13 14:07

from django.db import migrations, models
import stackoverflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0019_auto_20210413_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=stackoverflow.models.user_directory_path),
        ),
    ]
